package com.edavalos.mtx.util.string;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Generated by ChatGPT
 * <a href="https://imgur.com/a/YdQVveT"> chatGPT screenshots</a>
 */
public final class MtxTrieTest {

    @Test
    public void testInsertAndSearch() {
        MtxTrie trie = new MtxTrie();
        trie.insert("hello");
        trie.insert("world");
        assertTrue(trie.search("hello"));
        assertTrue(trie.search("world"));
        assertFalse(trie.search("foo"));
        assertFalse(trie.search("helloworld"));
    }

    @Test
    public void testStartsWith() {
        MtxTrie trie = new MtxTrie();
        trie.insert("hello");
        trie.insert("world");
        assertTrue(trie.startsWith("h"));
        assertTrue(trie.startsWith("w"));
        assertFalse(trie.startsWith("f"));
        assertFalse(trie.startsWith("helloworld"));
    }

    @Test
    public void testEmptyTrie() {
        MtxTrie trie = new MtxTrie();
        assertFalse(trie.search("hello"));
        assertFalse(trie.startsWith("h"));
    }
}
