package com.edavalos.mtx.util.string;

import java.util.HashMap;
import java.util.Map;

/**
 * An MtxStringTrie is a prefix tree, which is a tree-like data structure that stores a collection of strings. It is
 * useful for searching for all words with a given prefix in a set of strings.
 * <p> </p>
 * <a href="https://imgur.com/a/YdQVveT"> Generated by ChatGPT</a>
 */
public final class MtxStringTrie {
    private class MtxTrieNode {
        Map<Character, MtxTrieNode> children;
        boolean isWord;

        public MtxTrieNode() {
            children = new HashMap<>();
            isWord = false;
        }
    }

    private final MtxTrieNode root;

    public MtxStringTrie() {
        root = new MtxTrieNode();
    }

    public void insert(String word) {
        MtxTrieNode node = root;
        for (char c : word.toCharArray()) {
            if (!node.children.containsKey(c)) {
                node.children.put(c, new MtxTrieNode());
            }
            node = node.children.get(c);
        }
        node.isWord = true;
    }

    public boolean search(String word) {
        MtxTrieNode node = root;
        for (char c : word.toCharArray()) {
            if (!node.children.containsKey(c)) {
                return false;
            }
            node = node.children.get(c);
        }
        return node.isWord;
    }

    public boolean startsWith(String prefix) {
        MtxTrieNode node = root;
        for (char c : prefix.toCharArray()) {
            if (!node.children.containsKey(c)) {
                return false;
            }
            node = node.children.get(c);
        }
        return true;
    }
}
