package com.edavalos.mtx.util.string;

import java.util.HashMap;
import java.util.Map;

/**
 * Generated by ChatGPT
 * <a href="https://www.icloud.com/iclouddrive/0d7fUjTh7WQ_wzioUevhyAlOQ#trie%2CchatGPT%2C5-11-2023">
 *     chatGPT screenshots</a>
 */
public final class MtxTrie {
    private class MtxTrieNode {
        Map<Character, MtxTrieNode> children;
        boolean isWord;

        public MtxTrieNode() {
            children = new HashMap<>();
            isWord = false;
        }
    }

    private final MtxTrieNode root;

    public MtxTrie() {
        root = new MtxTrieNode();
    }

    public void insert(String word) {
        MtxTrieNode node = root;
        for (char c : word.toCharArray()) {
            if (!node.children.containsKey(c)) {
                node.children.put(c, new MtxTrieNode());
            }
            node = node.children.get(c);
        }
        node.isWord = true;
    }

    public boolean search(String word) {
        MtxTrieNode node = root;
        for (char c : word.toCharArray()) {
            if (!node.children.containsKey(c)) {
                return false;
            }
            node = node.children.get(c);
        }
        return node.isWord;
    }

    public boolean startsWith(String prefix) {
        MtxTrieNode node = root;
        for (char c : prefix.toCharArray()) {
            if (!node.children.containsKey(c)) {
                return false;
            }
            node = node.children.get(c);
        }
        return true;
    }
}
